=== tramanh9999/CrawlerEven/web/outputXML/category.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT categories (category*)>
        <!ELEMENT category (name, url)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT url (#PCDATA)>

=== tramanh9999/CrawlerEven/web/outputXML/category.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE categories SYSTEM "web/outputXML/category.dtd">
<categories>
    <category>
        <name>https://xemphimsoz.com/the-loai/phim-vo-thuat/</name>
        <url>Phim Võ Thuật</url>
    </category>
    <category>
        <name>https://xemphimsoz.com/the-loai/phim-hanh-dong/</name>
        <url>Phim Hành Động</url>
    </category>
    <category>
        <name>https://xemphimsoz.com/the-loai/phim-kinh-di/</name>
        <url>Phim Kinh Dị</url>
    </category>
    <category>
        <name>https://xemphimsoz.com/the-loai/phim-hoat-hinh/</name>
        <url>Phim Hoạt Hình</url>
    </category>
    <category>
        <name>https://xemphimsoz.com/the-loai/phim-hai-huoc/</name>
        <url>Phim Hài Hước</url>
    </category>
    <category>
        <name>https://xemphimsoz.com/the-loai/phim-hinh-su/</name>
        <url>Phim Hình Sự</url>
    </category>
    <category>
        <name>https://xemphimsoz.com/the-loai/phim-phieu-luu/</name>
        <url>Phim Phiêu Lưu</url>
    </category>
    <category>
        <name>https://xemphimsoz.com/the-loai/phim-tam-ly/</name>
        <url>Phim Tâm Lý</url>
    </category>
    <category>
        <name>https://xemphimsoz.com/the-loai/phim-thuyet-minh/</name>
        <url>Phim Thuyết Minh</url>
    </category>
    <category>
        <name>https://xemphimsoz.com/the-loai/phim-ma/</name>
        <url>Phim Ma</url>
    </category>
    <category>
        <name>https://xemphimsoz.com/the-loai/phim-vien-tuong/</name>
        <url>Phim Viễn Tưởng</url>
    </category>
    <category>
        <name>https://xemphimsoz.com/the-loai/phim-chieu-rap-2/</name>
        <url>Phim Chiếu Rạp</url>
    </category>
    <category>
        <name>https://xemphimsoz.com/the-loai/phim-tinh-cam-1/</name>
        <url>Phim Tình Cảm</url>
    </category>
    <category>
        <name>https://xemphimsoz.com/the-loai/phim-chien-tranh/</name>
        <url>Phim Chiến Tranh</url>
    </category>
    <category>
        <name>https://xemphimsoz.com/the-loai/phim-da-su/</name>
        <url>Phim Dã Sữ</url>
    </category>
    <category>
        <name>https://xemphimsoz.com/the-loai/phim-am-nhac/</name>
        <url>Phim Âm Nhạc</url>
    </category>
    <category>
        <name>https://xemphimsoz.com/the-loai/phim-than-thoai/</name>
        <url>Phim Thần Thoại</url>
    </category>
    <category>
        <name>https://xemphimsoz.com/the-loai/phim-kiem-hiep/</name>
        <url>Phim Kiếm Hiệp</url>
    </category>
    <category>
        <name>https://xemphimsoz.com/the-loai/phim-the-thao/</name>
        <url>Phim Thể Thao</url>
    </category>
</categories>
