=== tramanh9999/CrawlerEven/web/outputXML/movie.dtd
<?xml encoding="UTF-8"?>
        <!ELEMENT movie (title1*,title2*,subTitle*,audio*,imdb*,vote*,publishYear*,
                country*,introduction*,duration*)>
        <!ELEMENT title1 (#PCDATA)>
        <!ELEMENT title2 (#PCDATA)>
        <!ELEMENT subTitle (#PCDATA)>
        <!ELEMENT audio (#PCDATA)>
        <!ELEMENT imdb (#PCDATA)>
        <!ELEMENT vote (#PCDATA)>
        <!ELEMENT publishYear (#PCDATA)>
        <!ELEMENT country (#PCDATA)>
        <!ELEMENT introduction (#PCDATA)>
        <!ELEMENT duration (#PCDATA)>

=== tramanh9999/CrawlerEven/web/outputXML/movie.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE movie SYSTEM "web/outputXML/movie.dtd">
<movie>
    <title1>Tình Nhân Kết</title1>
    <title2>A Time To Love (2005)</title2>
    <subTitle/>
    <audio/>
    <imdb>N/a</imdb>
    <vote>0</vote>
    <publishYear>https://xemphimsoz.com/quoc-gia/phim-trung-quoc-1/</publishYear>
    <country>https://xemphimsoz.com/quoc-gia/phim-trung-quoc-1/</country>
    <introduction/>
    <duration>:  113 phút</duration>
</movie>
